### ISSUE TITLE
wich command for deploy with mi public IP?

### ISSUE THREAD

**Issue by johnfelipe** [Azarattum/Astrobot#16]

**Comment by Azarattum** [comment]
Hello. If you want to deploy this for yourself you need prebuilt files from *./dist* (or you might wanna build your own) and the *./assets* folder which contains the premade models. Then you can serve these files with any static web server. *index.html* will be your entry point. Check out the *gh-pages* branch for how that might look like.

Let me know if you have any issues.

**Comment by johnfelipe** [comment]
then only need nginx and thats all?

**Comment by Azarattum** [comment]
Yeah, that should be enough. All the machine learning stuff happens right in the browser, so there is no actual backend needed for the project.
